version: '3.7'

services:
  standalone-chrome:
    image: standalone-chrome
    ports:
      - 4444:4444
    container_name: standalone-chrome
  score-inquiry:
    image: score-inquiry
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:50080
    volumes:
      - ./:/app
    container_name: score-inquiry
